version: '3.7'
services:
  dev:
    build: .
    image: alynas.dev
    container_name: alynas.dev
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./balti_zirgai:/app
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn balti_zirgai.wsgi --bind 0.0.0.0:8000"
  nginx:
    build: ./nginx/
    image: nginx:balit_zirgai
    container_name: balti_zirgai.nginx
    restart: always
    ports: 
      - 80:80
    links:
      - dev:alynas
    volumes:
      - ./balti_zirgai/static:/app/static
      - ./balti_zirgai/media:/app/media
    